# TCL File Generated by Component Editor 11.0sp1
# Mon Nov 04 09:54:36 CET 2019
# DO NOT MODIFY


# +-----------------------------------
# | 
# | F1_1_valide "F1_1_valide" v1.0
# | null 2019.11.04.09:54:36
# | 
# | 
# | C:/Users/Etudiant/Documents/ROUTIER_OTAL_FPGA_M2/Barre_Franche/Code_embarqué/F1_Conversion_infos_vent/F1_1/F1_1_valide.vhd
# | 
# |    ./F1_1_valide.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module F1_1_valide
# | 
set_module_property NAME F1_1_valide
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Other
set_module_property DISPLAY_NAME F1_1_valide
set_module_property TOP_LEVEL_HDL_FILE F1_1_valide.vhd
set_module_property TOP_LEVEL_HDL_MODULE F1_1_valide
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME F1_1_valide
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file F1_1_valide.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock ""
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ENABLED true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0

set_interface_property clock_sink ENABLED true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink_1
# | 
add_interface clock_sink_1 clock end
set_interface_property clock_sink_1 clockRate 0

set_interface_property clock_sink_1 ENABLED true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end ARaz_n export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end_1
# | 
add_interface conduit_end_1 conduit end

set_interface_property conduit_end_1 ENABLED true

add_interface_port conduit_end_1 Freq_anemometre beginbursttransfer_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end_2
# | 
add_interface conduit_end_2 conduit end

set_interface_property conduit_end_2 ENABLED true

add_interface_port conduit_end_2 Continu beginbursttransfer_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end_3
# | 
add_interface conduit_end_3 conduit end

set_interface_property conduit_end_3 ENABLED true

add_interface_port conduit_end_3 Start_Stop beginbursttransfer_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end_4
# | 
add_interface conduit_end_4 conduit end

set_interface_property conduit_end_4 ENABLED true

add_interface_port conduit_end_4 Data_valide readdatavalid_n Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end_5
# | 
add_interface conduit_end_5 conduit end

set_interface_property conduit_end_5 ENABLED true

add_interface_port conduit_end_5 Data_anemometre readdata Output 8
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink_2
# | 
add_interface clock_sink_2 clock end
set_interface_property clock_sink_2 clockRate 0

set_interface_property clock_sink_2 ENABLED true

add_interface_port clock_sink_2 Clk_50M clk Input 1
# | 
# +-----------------------------------
